FROM tiangolo/uwsgi-nginx-flask:python3.8
COPY /api/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
RUN apt update
RUN apt install net-tools
COPY /api/nginx.conf /app/nginx.conf
COPY /api/uwsgi.ini /app/uwsgi.ini
COPY /core /app/core
COPY /api/routes /app/app/routes
COPY /api/main.py /app/app/main.py
COPY /api/openapi.yaml /app/app/openapi.yaml
WORKDIR /app/app
ENV LISTEN_PORT 5000
EXPOSE 5000
#ENTRYPOINT [ "python", "app/main.py" ]
#CMD [ "--env", "(env)", "--port", "(port)" ]
