name: .env-clip_zip_ship_admin
dependencies:
- psycopg2
- requests
- python-dateutil~=2.8.2
- requests~=2.26.0
- xmltodict~=0.12.0
- Flask>=0.10.1
- Flask-JWT-Extended
- flask-cors
- bcrypt~=3.2.0
- connexion[swagger-ui]~=2.9.0
- connexion>=2.2.0
- pip
- pip:
  - json2table
